# Databricks notebook source
# MAGIC %md
# MAGIC # 004 - Camada Gold — Modelagem Dimensional (Silver → Gold)
# MAGIC
# MAGIC **Objetivo:** Modelar e popular as tabelas dimensionais e a tabela fato seguindo a metodologia **Ralph Kimball (Star Schema)**.
# MAGIC
# MAGIC ### Modelo Estrela implementado:
# MAGIC
# MAGIC ```
# MAGIC                    ┌──────────────┐
# MAGIC                    │  DIM_TEMPO   │
# MAGIC                    └──────┬───────┘
# MAGIC                           │ FK_TEMPO
# MAGIC ┌────────────┐    ┌───────┴────────┐    ┌─────────────────┐
# MAGIC │  DIM_CARRO │────│  FATO_SINISTRO │────│  DIM_LOCALIDADE │
# MAGIC └────────────┘    └───────┬────────┘    └─────────────────┘
# MAGIC                           │ FK_CLIENTE
# MAGIC                    ┌──────┴───────┐
# MAGIC                    │  DIM_CLIENTE │
# MAGIC                    └──────────────┘
# MAGIC ```
# MAGIC
# MAGIC | Tabela | Tipo | Surrogate Key | Descrição |
# MAGIC |--------|------|---------------|-----------|
# MAGIC | `gold.dim_carro`      | Dimensão | `SK_CARRO`       | Veículos com marca e modelo desnormalizados |
# MAGIC | `gold.dim_cliente`    | Dimensão | `SK_CLIENTE`     | Clientes segurados |
# MAGIC | `gold.dim_localidade` | Dimensão | `SK_LOCALIDADE`  | Localidade hierárquica (município > estado > região) |
# MAGIC | `gold.dim_tempo`      | Dimensão | `DATA` (NK)      | Calendário de 2023 a 2026 |
# MAGIC | `gold.fato_sinistro`  | Fato     | —                | Sinistros com métricas e FKs para as dimensões |

# COMMAND ----------

# MAGIC %md
# MAGIC ## 1. Carregar tabelas Silver nos DataFrames

# COMMAND ----------

df_apolice   = spark.read.format("delta").table("silver.apolice")
df_carro     = spark.read.format("delta").table("silver.carro")
df_cliente   = spark.read.format("delta").table("silver.cliente")
df_endereco  = spark.read.format("delta").table("silver.endereco")
df_estado    = spark.read.format("delta").table("silver.estado")
df_marca     = spark.read.format("delta").table("silver.marca")
df_modelo    = spark.read.format("delta").table("silver.modelo")
df_municipio = spark.read.format("delta").table("silver.municipio")
df_regiao    = spark.read.format("delta").table("silver.regiao")
df_sinistro  = spark.read.format("delta").table("silver.sinistro")
df_telefone  = spark.read.format("delta").table("silver.telefone")

print("Tabelas Silver carregadas!")

# COMMAND ----------

# MAGIC %md
# MAGIC ## 2. DIM_CARRO — Dimensão Veículo
# MAGIC
# MAGIC Une as tabelas `carro`, `modelo` e `marca` para criar uma dimensão desnormalizada.
# MAGIC A **Surrogate Key (SK_CARRO)** é gerada automaticamente pelo Delta (IDENTITY).

# COMMAND ----------

# MAGIC %sql
# MAGIC DROP TABLE IF EXISTS gold.dim_carro;

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE gold.dim_carro (
# MAGIC   SK_CARRO   BIGINT GENERATED BY DEFAULT AS IDENTITY,
# MAGIC   PLACA      VARCHAR(10),
# MAGIC   MARCA      VARCHAR(100),
# MAGIC   MODELO     VARCHAR(100),
# MAGIC   COR        VARCHAR(20),
# MAGIC   ANO        INT,
# MAGIC   CHASSI     VARCHAR(25)
# MAGIC ) USING DELTA
# MAGIC COMMENT 'Dimensão Veículo — desnormalizada com marca e modelo';

# COMMAND ----------

df_modelo.createOrReplaceTempView("modelo")
df_marca.createOrReplaceTempView("marca")
df_carro.createOrReplaceTempView("carro")

# COMMAND ----------

# MAGIC %sql
# MAGIC -- MERGE SCD Type 1: atualiza se mudou, insere se não existe
# MAGIC WITH carros_relacional AS (
# MAGIC   SELECT c.PLACA,
# MAGIC          ma.NOME_MARCA,
# MAGIC          mo.NOME_MODELO,
# MAGIC          c.COR,
# MAGIC          c.ANO,
# MAGIC          c.CHASSI
# MAGIC     FROM carro c
# MAGIC          INNER JOIN modelo mo ON c.CODIGO_MODELO = mo.CODIGO_MODELO
# MAGIC          INNER JOIN marca  ma ON mo.CODIGO_MARCA  = ma.CODIGO_MARCA
# MAGIC )
# MAGIC MERGE INTO gold.dim_carro AS d
# MAGIC USING carros_relacional    AS s
# MAGIC ON d.PLACA = s.PLACA
# MAGIC
# MAGIC WHEN MATCHED AND (
# MAGIC     d.MARCA  <> s.NOME_MARCA  OR
# MAGIC     d.MODELO <> s.NOME_MODELO OR
# MAGIC     d.COR    <> s.COR         OR
# MAGIC     d.ANO    <> s.ANO         OR
# MAGIC     d.CHASSI <> s.CHASSI
# MAGIC ) THEN
# MAGIC   UPDATE SET PLACA  = s.PLACA,
# MAGIC              MARCA  = s.NOME_MARCA,
# MAGIC              MODELO = s.NOME_MODELO,
# MAGIC              COR    = s.COR,
# MAGIC              ANO    = s.ANO,
# MAGIC              CHASSI = s.CHASSI
# MAGIC
# MAGIC WHEN NOT MATCHED THEN
# MAGIC   INSERT (PLACA, MARCA, MODELO, COR, ANO, CHASSI)
# MAGIC   VALUES (s.PLACA, s.NOME_MARCA, s.NOME_MODELO, s.COR, s.ANO, s.CHASSI);

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT * FROM gold.dim_carro LIMIT 10;

# COMMAND ----------

# MAGIC %md
# MAGIC ## 3. DIM_TEMPO — Dimensão Calendário
# MAGIC
# MAGIC Gerada programaticamente para o intervalo de 2023 a 2026.

# COMMAND ----------

# MAGIC %sql
# MAGIC DROP TABLE IF EXISTS gold.dim_tempo;

# COMMAND ----------

from pyspark.sql.functions import expr

data_inicial = "2023-01-01"
data_final   = "2026-12-31"

num_dias = spark.sql(f"SELECT datediff('{data_final}', '{data_inicial}')").collect()[0][0]

df_tempo = (
    spark.range(0, num_dias + 1)
    .selectExpr(f"date_add(to_date('{data_inicial}'), CAST(id AS INT)) AS DATA")
    .selectExpr(
        "DATA",
        "year(DATA)  AS ANO",
        "month(DATA) AS MES",
        """(CASE month(DATA)
            WHEN 1  THEN 'JANEIRO'   WHEN 2  THEN 'FEVEREIRO' WHEN 3  THEN 'MARCO'
            WHEN 4  THEN 'ABRIL'     WHEN 5  THEN 'MAIO'      WHEN 6  THEN 'JUNHO'
            WHEN 7  THEN 'JULHO'     WHEN 8  THEN 'AGOSTO'    WHEN 9  THEN 'SETEMBRO'
            WHEN 10 THEN 'OUTUBRO'   WHEN 11 THEN 'NOVEMBRO'  WHEN 12 THEN 'DEZEMBRO'
           END) AS NOME_MES""",
        "day(DATA) AS DIA",
        """(CASE dayofweek(DATA)
            WHEN 1 THEN 'DOMINGO'       WHEN 2 THEN 'SEGUNDA-FEIRA'
            WHEN 3 THEN 'TERCA-FEIRA'   WHEN 4 THEN 'QUARTA-FEIRA'
            WHEN 5 THEN 'QUINTA-FEIRA'  WHEN 6 THEN 'SEXTA-FEIRA'
            WHEN 7 THEN 'SABADO'
           END) AS NOME_DIA_SEMANA""",
        "dayofweek(DATA) AS NUMERO_DIA_SEMANA",
        "quarter(DATA)   AS TRIMESTRE"
    )
)

df_tempo.display()
df_tempo.write.mode("overwrite").format("delta").saveAsTable("gold.dim_tempo")
print(f"✅ dim_tempo criada com {df_tempo.count()} registros")

# COMMAND ----------

# MAGIC %md
# MAGIC ## 4. DIM_CLIENTE — Dimensão Cliente

# COMMAND ----------

# MAGIC %sql
# MAGIC DROP TABLE IF EXISTS gold.dim_cliente;

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE gold.dim_cliente (
# MAGIC   SK_CLIENTE       BIGINT GENERATED BY DEFAULT AS IDENTITY,
# MAGIC   CODIGO_CLIENTE   INT,
# MAGIC   NOME             VARCHAR(100),
# MAGIC   CPF              VARCHAR(14),
# MAGIC   SEXO             CHAR(1),
# MAGIC   DATA_NASCIMENTO  DATE
# MAGIC ) USING DELTA
# MAGIC COMMENT 'Dimensão Cliente — segurados com apólice ativa';

# COMMAND ----------

df_cliente.createOrReplaceTempView("cliente")

# COMMAND ----------

# MAGIC %sql
# MAGIC WITH cliente_relacional AS (
# MAGIC   SELECT CODIGO_CLIENTE,
# MAGIC          NOME_CLIENTE  AS NOME,
# MAGIC          CPF,
# MAGIC          SEXO,
# MAGIC          DATA_NASCIMENTO
# MAGIC     FROM cliente
# MAGIC )
# MAGIC MERGE INTO gold.dim_cliente AS d
# MAGIC USING cliente_relacional    AS r
# MAGIC ON r.CODIGO_CLIENTE = d.CODIGO_CLIENTE
# MAGIC
# MAGIC WHEN MATCHED AND (
# MAGIC     r.NOME            <> d.NOME            OR
# MAGIC     r.CPF             <> d.CPF             OR
# MAGIC     r.SEXO            <> d.SEXO            OR
# MAGIC     r.DATA_NASCIMENTO <> d.DATA_NASCIMENTO
# MAGIC ) THEN
# MAGIC   UPDATE SET CODIGO_CLIENTE   = r.CODIGO_CLIENTE,
# MAGIC              NOME             = r.NOME,
# MAGIC              CPF              = r.CPF,
# MAGIC              SEXO             = r.SEXO,
# MAGIC              DATA_NASCIMENTO  = r.DATA_NASCIMENTO
# MAGIC
# MAGIC WHEN NOT MATCHED THEN
# MAGIC   INSERT (CODIGO_CLIENTE, NOME, CPF, SEXO, DATA_NASCIMENTO)
# MAGIC   VALUES (r.CODIGO_CLIENTE, r.NOME, r.CPF, r.SEXO, r.DATA_NASCIMENTO);

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT * FROM gold.dim_cliente LIMIT 10;

# COMMAND ----------

# MAGIC %md
# MAGIC ## 5. DIM_LOCALIDADE — Hierarquia Município > Estado > Região

# COMMAND ----------

# MAGIC %sql
# MAGIC DROP TABLE IF EXISTS gold.dim_localidade;

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE gold.dim_localidade (
# MAGIC   SK_LOCALIDADE    BIGINT GENERATED BY DEFAULT AS IDENTITY,
# MAGIC   CODIGO_MUNICIPIO INT,
# MAGIC   NOME_MUNICIPIO   VARCHAR(100),
# MAGIC   SIGLA_ESTADO     VARCHAR(2),
# MAGIC   NOME_ESTADO      VARCHAR(100),
# MAGIC   NOME_REGIAO      VARCHAR(50)
# MAGIC ) USING DELTA
# MAGIC COMMENT 'Dimensão Localidade — hierarquia geográfica completa';

# COMMAND ----------

df_municipio.createOrReplaceTempView("municipio")
df_estado.createOrReplaceTempView("estado")
df_regiao.createOrReplaceTempView("regiao")

# COMMAND ----------

# MAGIC %sql
# MAGIC WITH localidade_relacional AS (
# MAGIC   SELECT m.CODIGO_MUNICIPIO,
# MAGIC          m.NOME_MUNICIPIO,
# MAGIC          e.UF AS SIGLA_ESTADO,
# MAGIC          e.NOME_ESTADO,
# MAGIC          r.NOME_REGIAO
# MAGIC     FROM municipio m
# MAGIC          INNER JOIN estado e ON m.CODIGO_ESTADO = e.CODIGO_ESTADO
# MAGIC          INNER JOIN regiao  r ON e.CODIGO_REGIAO  = r.CODIGO_REGIAO
# MAGIC )
# MAGIC MERGE INTO gold.dim_localidade AS d
# MAGIC USING localidade_relacional    AS r
# MAGIC ON r.CODIGO_MUNICIPIO = d.CODIGO_MUNICIPIO
# MAGIC
# MAGIC WHEN MATCHED AND (
# MAGIC     r.NOME_MUNICIPIO <> d.NOME_MUNICIPIO OR
# MAGIC     r.NOME_ESTADO    <> d.NOME_ESTADO    OR
# MAGIC     r.NOME_REGIAO    <> d.NOME_REGIAO
# MAGIC ) THEN
# MAGIC   UPDATE SET CODIGO_MUNICIPIO = r.CODIGO_MUNICIPIO,
# MAGIC              NOME_MUNICIPIO   = r.NOME_MUNICIPIO,
# MAGIC              SIGLA_ESTADO     = r.SIGLA_ESTADO,
# MAGIC              NOME_ESTADO      = r.NOME_ESTADO,
# MAGIC              NOME_REGIAO      = r.NOME_REGIAO
# MAGIC
# MAGIC WHEN NOT MATCHED THEN
# MAGIC   INSERT (CODIGO_MUNICIPIO, NOME_MUNICIPIO, SIGLA_ESTADO, NOME_ESTADO, NOME_REGIAO)
# MAGIC   VALUES (r.CODIGO_MUNICIPIO, r.NOME_MUNICIPIO, r.SIGLA_ESTADO, r.NOME_ESTADO, r.NOME_REGIAO);

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT * FROM gold.dim_localidade;

# COMMAND ----------

# MAGIC %md
# MAGIC ## 6. FATO_SINISTRO — Tabela Fato
# MAGIC
# MAGIC Granularidade: **um sinistro por linha**. Métricas: quantidade e valor do prejuízo.

# COMMAND ----------

# MAGIC %sql
# MAGIC DROP TABLE IF EXISTS gold.fato_sinistro;

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE gold.fato_sinistro (
# MAGIC   FK_TEMPO         DATE    COMMENT 'Chave para dim_tempo',
# MAGIC   FK_LOCALIDADE    BIGINT  COMMENT 'SK da dim_localidade',
# MAGIC   FK_CARRO         BIGINT  COMMENT 'SK da dim_carro',
# MAGIC   FK_CLIENTE       BIGINT  COMMENT 'SK da dim_cliente',
# MAGIC   QTDE_SINISTRO    INT     COMMENT 'Quantidade de sinistros no grupo',
# MAGIC   VALOR_PREJUIZO   DECIMAL(15,2) COMMENT 'Soma do valor de prejuízo'
# MAGIC ) USING DELTA
# MAGIC COMMENT 'Fato Sinistro — granularidade por data, localidade, carro e cliente';

# COMMAND ----------

df_apolice.createOrReplaceTempView("apolice")
df_sinistro.createOrReplaceTempView("sinistro")

# COMMAND ----------

# MAGIC %sql
# MAGIC INSERT INTO gold.fato_sinistro
# MAGIC WITH apolice_cliente AS (
# MAGIC   SELECT a.CODIGO_CLIENTE, a.PLACA
# MAGIC     FROM apolice a
# MAGIC )
# MAGIC SELECT s.DATA_SINISTRO                   AS FK_TEMPO,
# MAGIC        dloc.SK_LOCALIDADE                AS FK_LOCALIDADE,
# MAGIC        dcar.SK_CARRO                     AS FK_CARRO,
# MAGIC        dcli.SK_CLIENTE                   AS FK_CLIENTE,
# MAGIC        COUNT(1)                          AS QTDE_SINISTRO,
# MAGIC        SUM(s.VALOR_PREJUIZO)             AS VALOR_PREJUIZO
# MAGIC   FROM sinistro s
# MAGIC        INNER JOIN gold.dim_carro       dcar ON s.PLACA                = dcar.PLACA
# MAGIC        INNER JOIN apolice_cliente      ac   ON ac.PLACA               = s.PLACA
# MAGIC        INNER JOIN gold.dim_cliente     dcli ON ac.CODIGO_CLIENTE      = dcli.CODIGO_CLIENTE
# MAGIC        INNER JOIN gold.dim_localidade  dloc ON s.CODIGO_LOCAL_SINISTRO= dloc.CODIGO_MUNICIPIO
# MAGIC        INNER JOIN gold.dim_tempo       dtem ON s.DATA_SINISTRO        = dtem.DATA
# MAGIC GROUP BY s.DATA_SINISTRO, dloc.SK_LOCALIDADE, dcar.SK_CARRO, dcli.SK_CLIENTE;

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT * FROM gold.fato_sinistro LIMIT 20;

# COMMAND ----------

# MAGIC %md
# MAGIC ## 7. Verificar todas as tabelas Gold criadas

# COMMAND ----------

# MAGIC %sql
# MAGIC SHOW TABLES IN gold;

# COMMAND ----------

# MAGIC %md
# MAGIC ## 8. Query analítica — Top 5 localidades com mais sinistros

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT dl.NOME_MUNICIPIO,
# MAGIC        dl.NOME_ESTADO,
# MAGIC        dl.NOME_REGIAO,
# MAGIC        SUM(fs.QTDE_SINISTRO)  AS TOTAL_SINISTROS,
# MAGIC        SUM(fs.VALOR_PREJUIZO) AS TOTAL_PREJUIZO
# MAGIC   FROM gold.fato_sinistro fs
# MAGIC        INNER JOIN gold.dim_localidade dl ON fs.FK_LOCALIDADE = dl.SK_LOCALIDADE
# MAGIC GROUP BY dl.NOME_MUNICIPIO, dl.NOME_ESTADO, dl.NOME_REGIAO
# MAGIC ORDER BY TOTAL_SINISTROS DESC
# MAGIC LIMIT 10;

# COMMAND ----------

# MAGIC %md
# MAGIC ## 9. Query analítica — Sinistros por ano e mês

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT dt.ANO,
# MAGIC        dt.NOME_MES,
# MAGIC        dt.MES,
# MAGIC        SUM(fs.QTDE_SINISTRO)  AS TOTAL_SINISTROS,
# MAGIC        SUM(fs.VALOR_PREJUIZO) AS TOTAL_PREJUIZO
# MAGIC   FROM gold.fato_sinistro fs
# MAGIC        INNER JOIN gold.dim_tempo dt ON fs.FK_TEMPO = dt.DATA
# MAGIC GROUP BY dt.ANO, dt.NOME_MES, dt.MES
# MAGIC ORDER BY dt.ANO, dt.MES;
